### ISSUE TITLE
Script seems to crash after trying to open firefox 

### ISSUE THREAD

**Issue by GijsSi** [unix121/gmail-generator#2]
➜  source git:(master) ✗ python3 gmail_generator.py
> Opening Firefox...
Traceback (most recent call last):
  File "gmail_generator.py", line 180, in <module>
    if open_firefox() :
  File "gmail_generator.py", line 45, in open_firefox
    _location_=pyautogui.center(_start_button_)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyscreeze/__init__.py", line 407, in center
    return (coords[0] + int(coords[2] / 2), coords[1] + i

**Comment by stav121** [comment]
Hey man, 

That's probably something to do with PyAutoGUI, I would try to look for an answer there.

**Comment by seanturner026** [comment]
I'm also having a different issue with a crash after trying to open firefox. Maybe an anaconda problem?

```
> Opening Firefox...
Traceback (most recent call last):
  File "gmail_generator.py", line 180, in <module>
    if open_firefox() :
  File "gmail_generator.py", line 45, in open_firefox
    _location_=pyautogui.center(_start_button_)
  File "/anaconda/lib/python3.6/site-packages/pyscreeze/__init__.py", line 407, in center
    return (coords[0] + int(coords[2] / 2), coords[1] + int(coords[3] / 2))
TypeError: 'NoneType' object is not subscriptable
```

**Comment by stav121** [comment]
I'll investigate the issue soon, I haven't really run this script in months so I'll give it a go again and find the issue.

**Comment by var-che** [comment]
I have the same problem as Sean. Any updates on this bug?

**Comment by stav121** [comment]
First chance I get I will fully update the script. I'm just kinda busy those days.

**Comment by stav121** [comment]
(Closed it accidentally)

**Comment by nkthuan** [comment]
@unix121 Pal, you are doing it in a too overly complex way. 
First, why finding the Firefox browser by trying to click on the OS menu ? 
Why not simply this:
```
firefox_path = "C:/Program Files/Mozilla Firefox/firefox.exe"
cmdline = [firefox_path]
subprocess.Popen(cmdline)
```
For locating the form, the same problem. You should have some way to find a form with the specific ID / class in the page ...

I think all the crashing cases are due to this, I'm not sure exactly what you did with the images. Code just fail at those parts.

**Comment by stav121** [comment]
Hello @ramcrys ,
truth be told, the script is extremely outdated so it's here only for archiving purposes. If you are interested in bringing it back to life you are welcome to make changes and make a PR (or just fork the project and continue the way to like it). The script was written like years ago and I've not used it in years :)

**Comment by nkthuan** [comment]
After thinking about this, I speculate that what we are trying to achieve is actually somewhat "illegal". It's illegal in the sense that companies like Google are trying with their best to prevent spammers from using automatic scripts like this. 

So, though a useful tool in nature, I think it's best to actually stop it :D Personal tool at home is another story, but this won't do on Github. 

Yesterday I tried to find such a tool/script, but after second thought, it's pretty risky.

**Comment by stav121** [comment]
@ramcrys , as mentioned in the [about](https://github.com/unix121/gmail-generator#about) section of the repository, this script is for research purposes. The way that you chose to use the software is completely up to you.
