### ISSUE TITLE
error on kali 

### ISSUE THREAD

**Issue by accountdays** [unix121/gmail-generator#3]
python gmail_generator.py
> Opening Firefox...
Traceback (most recent call last):
  File "gmail_generator.py", line 180, in <module>
    if open_firefox() :
  File "gmail_generator.py", line 45, in open_firefox
    _location_=pyautogui.center(_start_button_)
  File "/usr/local/lib/python2.7/dist-packages/pyscreeze/__init__.py", line 407, in center
    return (coords[0] + int(coords[2] / 2), coords[1] + int(coords[3] / 2))
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by blooditrix** [comment]
this is due to pyautogui not being able to find the image while locating on the screen. Ive added a workaround for this which allows the script to get to the end of the account creation however am waiting to commit the phone verf until after im back on RHEL from kali.. lol

**Comment by faahiero** [comment]
> python gmail_generator.py
> 
> > Opening Firefox...
> > Traceback (most recent call last):
> > File "gmail_generator.py", line 180, in 
> > if open_firefox() :
> > File "gmail_generator.py", line 45, in open_firefox
> > _location_=pyautogui.center(_start_button_)
> > File "/usr/local/lib/python2.7/dist-packages/pyscreeze/**init**.py", line 407, in center
> > return (coords[0] + int(coords[2] / 2), coords[1] + int(coords[3] / 2))
> > TypeError: 'NoneType' object has no attribute '**getitem**'

go to /usr/local/lib/python2.7/dist-packages/pyscreeze/init.py and change the function center(coords) to

def center(coords):
    if coords is None:
        return coords
    else:
        return Point(coords[0] + int(coords[2] / 2), coords[1] + int(coords[3] / 2))
